### PR TITLE
Added support to use the document scroll instead of the element scroll

### PR DESCRIPTION
**Pull request by mathieumg**
Tried to preserve the style as much as possible. Let me know if anything is out of place.

### CODE REVIEW

**Comment by nrako** [comment]
That's interesting thanks @mathieumg.

Could you please add `useDocument` prop type with a short comment to the [readme](https://github.com/nrako/react-component-scrollload#prop-types), and I'll happily merge your PR.

**Comment by nrako** [comment]
Also for reference could you please describe in this PR a use case for this where using element scroll isn't sufficient?

**Comment by mathieumg** [comment]
Thanks! Yes, the use case is the following: The current implementation allows to load more items when you scroll within an element's container, for example a long table with a set `height` and a `overflow-y: scroll` CSS property. This PR adds the ability to load more items when the whole page is scrolled and the bottom of the element (minus the `treshold`) is about to enter the viewport. I think that might even be the most common use case, but I didn't want to make it default to `true` to break the current API.

I'll update the README shortly!

**Comment by mathieumg** [comment]
Made the change! Let me know if you want me to squash the commits.

**Comment by nrako** [comment]
:rocket: https://github.com/nrako/react-component-scrollload/releases/tag/0.3.0

**Comment by mathieumg** [comment]
Awesome, thank you! :sparkles:

**Pull request merged**
